### ISSUE TITLE
Mod Compatability is Invalid

### ISSUE THREAD

**Issue by AidenTran900** [bachittle/BeatSaberQuestModsList#3]
Lots of mods on the list are still compatible with 1.10.0 beat saber. Sure the mod compatibility shows up but that does not mean that it doesn't work anymore.

**Comment by AidenTran900** [comment]
I didn't read it well nvm

**Comment by bachittle** [comment]
I haven't touched this in a while as it didn't gain traction, feel free to update as you see fit or I'll do it when I'm motivated enough to do so 😄

**Comment by kartur** [comment]
I think it's important to have sources like this, because otherwise I need to start discord to find out where I can get the latest compatible mods and the mods are also all over various discord channels. Having it all in one list and also seeing if they are compatible with a download link is great.

I can report that "Mapping Extensions" and "No Health and Safety" work with 1.10.0

**Comment by bachittle** [comment]
closing this project. Not very impressed with how the community treated this project. They much prefer their own method of going through the discord. If you would like mods, do it their way, not going to contribute unless I come back to the community (I might do C++ work for actual mods because that part is fun).
